// File: src/app/models/event.model.ts

export interface EventShow {
    _id?: string; // Optional because MongoDB generates this field automatically
    event_name: string;
    event_location: {
      type: 'Point'; // GeoJSON type, always 'Point' as per the schema
      coordinates: [number, number]; // Array of two numbers: [longitude, latitude]
    };
    event_date: string; // Date stored as a string (YYYY-MM-DD format)
    event_time: string; // Time stored as a string (HH:mm format)
    event_address: string;
    sc_free?: number; // Optional because it has no default value in the schema
    sc_vip?: number; // Default value is 0
    sc_normal?: number; // Default value is 0
    sc_balcony?: number; // Default value is 0
    sc_front_row?: number; // Default value is 0
    price_vip?: string; // Default value is '0'
    price_normal?: string; // Default value is '0'
    price_balcony?: string; // Default value is '0'
    price_front_row?: string; // Default value is '0'
    cover_image: string;
    isFree?: boolean; // Default value is false
    isPaidOnly?: boolean; // Default value is true
    isCashinPerson?: boolean; // Default value is false
    isActive?: boolean; // Default value is true
    isCompleted?: boolean; // Default value is false
    created_date?: Date; // Optional because it's auto-generated by MongoDB
  }

  export interface User {
    _id?: string; // Optional because it is typically auto-generated by MongoDB
    firstName: string;
    lastName: string;
    mobile: string;
    address: string;
    email: string;
    password?: string; // Optional if not always required
    user_type: string;
    birthDay?: Date; // Optional if not always provided
    points?: number; // Optional if not always provided
    isaBusiness: boolean;
    businessName?: string; // Optional if only relevant for businesses
    businessAddress?: string; // Optional if only relevant for businesses
    businessType?: string; // Optional if only relevant for businesses
    businessCategory?: string; // Optional if only relevant for businesses
    subCategories?: string[]; // Optional array of strings
    logoPath?: string; // Optional if not always provided
    feature_image?: string; // Optional if not always provided
    unique_id?: string; // Optional if not always provided
    fcmToken?: string; // Optional if not always provided
    isjudge?: boolean; // Defaults to false if not provided
    location?: {
        type: 'Point'; // Fixed value from enum
        coordinates: [number, number]; // Array of two numbers
    };
    registerCode?: string; // Optional if not always provided
    createdDate?: Date; // Defaults to current date if not provided
    languageSettings?: string[]; // Optional array of strings
    countrySettings?: string[]; // Optional array of strings
}